// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk4GY-VkG4dd_zXP5HZQDlZbjdY0k0img',
    appId: '1:459965557703:web:780d1a11870a3031b887e2',
    messagingSenderId: '459965557703',
    projectId: 'fooddata-92fa8',
    authDomain: 'fooddata-92fa8.firebaseapp.com',
    storageBucket: 'fooddata-92fa8.firebasestorage.app',
    measurementId: 'G-1CL7MQ3Q41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3bDYoQqlXzfEmnCwJbrhexAr24O05BZI',
    appId: '1:459965557703:android:7ce99ccd25221369b887e2',
    messagingSenderId: '459965557703',
    projectId: 'fooddata-92fa8',
    storageBucket: 'fooddata-92fa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'fooddata-92fa8',
    storageBucket: 'fooddata-92fa8.appspot.com',
    iosBundleId: 'com.example.flutter-application-1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'fooddata-92fa8',
    storageBucket: 'fooddata-92fa8.appspot.com',
    iosBundleId: 'com.example.flutter-application-1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: 'your-windows-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'fooddata-92fa8',
    authDomain: 'fooddata-92fa8.firebaseapp.com',
    storageBucket: 'fooddata-92fa8.appspot.com',
  );
}